### ISSUE TITLE
RSS Feed para tu blog

### ISSUE THREAD

**Issue by cjduncana** [demogar/demogar#1]
¡Que xopá, Demo!

Veo que tu blog no tiene un feed de RSS. Te lo recomiendo ya que tendrás una manera de avisarle a la gente suscrita cuando creas un nuevo post. Aquí te dejo la guía de como implementarlo en Jekyll.
https://jekyllrb.com/tutorials/convert-site-to-jekyll/#10-rss-feed

Que la pases chevere, Chris 👍🏻

**Comment by demogar** [comment]
@cjduncana hola!, no había visto esto por acá así que de una vez lo agregué.

¡Gracias por la recomendación, no había siquiera pensado en agregarlo!

https://www.demogar.com/feed.xml

**Comment by cjduncana** [comment]
¡Éxito!

**Comment by cjduncana** [comment]
Puntos extra: Agregar el ícono de RSS con vínculo.

**Comment by demogar** [comment]
Hola @cjduncana !
Al final terminé moviendo todo a Gatsby (WIP), ahora estaría en:
https://www.demogar.com/rss.xml

Pensaré si agrego o no el ícono, por ahora estaría en el link property del html.

**Comment by demogar** [comment]
Agregado:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/94550/197366500-96a3da09-dd26-430c-9761-45c93ecefc82.png">
